# Generated by Django 5.2.16 on 2026-07-18 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Veranstaltungskategorie',
                'verbose_name_plural': 'Veranstaltungskategorien',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=280, verbose_name='Kurzbeschreibung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('start_at', models.DateTimeField(verbose_name='Beginn')),
                ('end_at', models.DateTimeField(verbose_name='Ende')),
                ('timezone_name', models.CharField(default='Europe/Zurich', max_length=64, verbose_name='Zeitzone')),
                ('location_name', models.CharField(max_length=200, verbose_name='Ort')),
                ('location_address', models.TextField(blank=True, verbose_name='Adresse')),
                ('map_url', models.URLField(blank=True, verbose_name='Karten- oder externe URL')),
                ('visibility', models.CharField(choices=[('public', 'Oeffentlich'), ('members', 'Nur Mitglieder'), ('selected_groups', 'Ausgewaehlte Gruppen'), ('selected_users', 'Ausgewaehlte Benutzer')], default='public', max_length=30, verbose_name='Sichtbarkeit')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'Zur Pruefung'), ('scheduled', 'Geplant'), ('published', 'Veroeffentlicht'), ('cancelled', 'Abgesagt'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veroeffentlicht am')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Geplant fuer')),
                ('signup_url', models.URLField(blank=True, verbose_name='Anmeldelink')),
                ('signup_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Anmeldefrist')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximale Teilnehmerzahl')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Versionsnummer')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='visible_events', to='auth.group', verbose_name='Erlaubte Gruppen')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='directly_visible_events', to=settings.AUTH_USER_MODEL, verbose_name='Erlaubte Benutzer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_hero_usages', to='media_library.mediaasset')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['start_at', 'title', 'pk'],
                'permissions': [('publish_event', 'Can publish events'), ('schedule_event', 'Can schedule events'), ('cancel_event', 'Can cancel events'), ('archive_event', 'Can archive events'), ('preview_event', 'Can preview events'), ('restore_event_revision', 'Can restore event revisions'), ('view_eventrevision', 'Can view event revisions')],
            },
        ),
        migrations.CreateModel(
            name='EventRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField(verbose_name='Revisionsnummer')),
                ('snapshot', models.JSONField(default=dict, verbose_name='Snapshot')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Aenderungsgrund')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'Zur Pruefung'), ('scheduled', 'Geplant'), ('published', 'Veroeffentlicht'), ('cancelled', 'Abgesagt'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_revisions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='events.event')),
            ],
            options={
                'ordering': ['-revision_number', '-created_at'],
                'unique_together': {('event', 'revision_number')},
            },
        ),
    ]
