# Generated by Django 5.2.16 on 2026-07-17 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(blank=True, max_length=32)),
                ('vulgar_name', models.CharField(blank=True, max_length=150, verbose_name='Vulgo')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('left_on', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('membership_status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('inactive', 'Inactive'), ('altherr', 'Alt-Froburger'), ('honorary', 'Honorary')], default='invited', max_length=20)),
                ('current_charge', models.CharField(blank=True, max_length=150)),
                ('directory_visibility', models.CharField(choices=[('private', 'Private'), ('members', 'Members only'), ('public', 'Public')], default='members', max_length=20)),
                ('short_bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name', 'user__email'],
                'permissions': [('manage_member_profiles', 'Can manage member profiles')],
            },
        ),
    ]
