# Generated by Django 5.2.16 on 2026-07-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ['user__last_name', 'user__first_name', 'user__email'], 'permissions': [('manage_member_profiles', 'Can manage member profiles'), ('view_sensitive_documents', 'Can view sensitive internal documents')]},
        ),
    ]
