# Generated by Django 5.2.16 on 2026-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_memberprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='membership_number',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='association_type',
            field=models.CharField(blank=True, choices=[('active', 'Aktiv'), ('af', 'AF')], max_length=20, verbose_name='Verein'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member_role',
            field=models.CharField(blank=True, max_length=150, verbose_name='Rolle'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='member_photos/', verbose_name='Profilfoto'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='current_charge',
            field=models.CharField(blank=True, max_length=150, verbose_name='Charge'),
        ),
    ]
