# Generated by Django 5.2.16 on 2026-07-17 09:24

from django.db import migrations, models


def migrate_member_role_to_member_roles(apps, schema_editor):
    MemberProfile = apps.get_model("members", "MemberProfile")
    role_map = {
        "bursch": "bursch",
        "fux": "fux",
        "web-x": "web_x",
        "web_x": "web_x",
    }

    for profile in MemberProfile.objects.all():
        raw_value = (profile.member_role or "").strip()
        if not raw_value:
            profile.member_roles = []
        else:
            normalized = []
            for chunk in raw_value.replace(";", ",").split(","):
                token = chunk.strip().lower()
                mapped = role_map.get(token)
                if mapped and mapped not in normalized:
                    normalized.append(mapped)
            profile.member_roles = normalized
        profile.save(update_fields=["member_roles"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_memberprofile_membership_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='member_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='Rollen'),
        ),
        migrations.RunPython(migrate_member_role_to_member_roles, noop_reverse),
        migrations.RemoveField(
            model_name='memberprofile',
            name='member_role',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='current_charge',
            field=models.CharField(blank=True, choices=[('senior', 'Senior'), ('consenior', 'Consenior'), ('fuxmajor', 'Fuxmajor'), ('aktuar', 'Aktuar'), ('questor', 'Questor')], max_length=20, verbose_name='Charge'),
        ),
    ]
