# Generated by Django 5.2.16 on 2026-07-18 17:01

import apps.members.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_memberprofile_member_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, storage=apps.members.storage.PrivateMemberPhotoStorage(), upload_to='member_photos/', verbose_name='Profilfoto'),
        ),
    ]
