# Generated by Django 5.2.16 on 2026-07-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('members', '0005_alter_memberprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=120, unique=True, verbose_name='Externer Schluessel')),
                ('display_name', models.CharField(max_length=160, verbose_name='Oeffentlicher Anzeigename')),
                ('vulgar_name', models.CharField(blank=True, max_length=120, verbose_name='Oeffentliches Vulgo')),
                ('function_title', models.CharField(blank=True, max_length=160, verbose_name='Funktion')),
                ('short_description', models.TextField(blank=True, verbose_name='Kurzbeschreibung')),
                ('group_key', models.CharField(choices=[('aktivitas_committee', 'Komitee der Aktivitas'), ('salon', 'Salon'), ('fuxenstall', 'Fuxenstall'), ('altherren_committee', 'Komitee der Alt-Froburger')], max_length=40, verbose_name='Gruppierung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_publicly_approved', models.BooleanField(default=False, verbose_name='Oeffentlich freigegeben')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_member_profiles', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Oeffentliches Mitglied',
                'verbose_name_plural': 'Oeffentliche Mitglieder',
                'ordering': ['group_key', 'sort_order', 'display_name', 'pk'],
            },
        ),
    ]
