# Generated by Django 5.2.16 on 2026-07-18 20:42

from html import escape

from django.db import migrations, models

SIMPLIFIED_POST_LAYOUTS = (
    {
        "key": "simple_classic",
        "name": "Klassisch",
        "description": "Ein uebersichtlicher Beitrag mit Titel, Einleitung und fortlaufendem Text.",
        "template_name": "public/posts/layouts/simple_classic.html",
    },
    {
        "key": "simple_focus",
        "name": "Fokus",
        "description": (
            "Fuer wichtige Mitteilungen mit grosser Ueberschrift "
            "und hervorgehobener Einleitung."
        ),
        "template_name": "public/posts/layouts/simple_focus.html",
    },
    {
        "key": "simple_magazine",
        "name": "Magazin",
        "description": (
            "Ein moderner Aufbau fuer Rueckblicke, Berichte "
            "und laengere Geschichten."
        ),
        "template_name": "public/posts/layouts/simple_magazine.html",
    },
)


def _paragraphs(value):
    chunks = []
    for paragraph in (part.strip() for part in value.split("\n\n")):
        if not paragraph:
            continue
        chunks.append(
            "<p>" + "<br>".join(escape(line.strip()) for line in paragraph.splitlines()) + "</p>"
        )
    return "".join(chunks)


def _build_body_html(post):
    fragments = []
    for block in post.blocks.order_by("position", "pk"):
        block_type = block.block_type
        heading = escape(block.heading or "")
        body = block.body or ""
        link_url = escape(block.link_url or "")
        link_label = escape(block.link_label or "")
        image = getattr(block, "image", None)
        carousel = getattr(block, "carousel", None)

        if block_type == "heading" and heading:
            fragments.append(f"<h2>{heading}</h2>")
        elif block_type == "text" and body:
            fragments.append(_paragraphs(body))
        elif block_type in {"quote", "notice"} and body:
            fragments.append(f"<blockquote>{_paragraphs(body)}</blockquote>")
        elif block_type == "divider":
            fragments.append("<hr>")
        elif block_type in {"image", "hero_image"} and image:
            alt_text = escape(image.alt_text or heading or "Beitragsbild")
            figure = [f'<figure><img src="{escape(image.file.url)}" alt="{alt_text}">']
            if image.caption:
                figure.append(f"<figcaption>{escape(image.caption)}</figcaption>")
            figure.append("</figure>")
            fragments.append("".join(figure))
        elif block_type == "image_text" and image:
            alt_text = escape(image.alt_text or heading or "Beitragsbild")
            fragments.append(
                f'<figure><img src="{escape(image.file.url)}" alt="{alt_text}"></figure>'
            )
            if body:
                fragments.append(_paragraphs(body))
            if link_url and link_label:
                fragments.append(f'<p><a href="{link_url}">{link_label}</a></p>')
        elif block_type == "cta" and link_url and link_label:
            fragments.append(f'<p><a href="{link_url}">{link_label}</a></p>')
        elif block_type in {"carousel", "gallery"} and carousel:
            for item in carousel.items.order_by("position", "pk"):
                if not item.is_active or not item.image:
                    continue
                alt_text = escape(item.image.alt_text or item.heading or "Beitragsbild")
                figure = [
                    f'<figure><img src="{escape(item.image.file.url)}" alt="{alt_text}">'
                ]
                if item.heading:
                    figure.append(f"<figcaption>{escape(item.heading)}</figcaption>")
                figure.append("</figure>")
                fragments.append("".join(figure))
                if item.body:
                    fragments.append(_paragraphs(item.body))
                if item.link_url and item.link_label:
                    fragments.append(
                        f'<p><a href="{escape(item.link_url)}">{escape(item.link_label)}</a></p>'
                    )
    return "".join(fragments)


def seed_simplified_post_layouts_and_body_html(apps, schema_editor):
    LayoutPreset = apps.get_model("content", "LayoutPreset")
    Post = apps.get_model("content", "Post")

    for preset in SIMPLIFIED_POST_LAYOUTS:
        LayoutPreset.objects.update_or_create(
            scope="post",
            key=preset["key"],
            defaults={
                "name": preset["name"],
                "description": preset["description"],
                "preview_static_path": "",
                "allowed_block_types": [],
                "required_fields": ["title", "teaser", "body_html"],
                "max_images": 1,
                "is_active": True,
            },
        )

    for post in Post.objects.prefetch_related(
        "blocks",
        "blocks__image",
        "blocks__carousel__items__image",
    ):
        changed_fields = []
        if post.status == "review":
            post.status = "draft"
            changed_fields.append("status")
        if not post.body_html:
            post.body_html = _build_body_html(post)
            changed_fields.append("body_html")
        if changed_fields:
            post.save(update_fields=changed_fields + ["updated_at"])


def remove_simplified_post_layouts(apps, schema_editor):
    LayoutPreset = apps.get_model("content", "LayoutPreset")
    LayoutPreset.objects.filter(
        scope="post",
        key__in=[preset["key"] for preset in SIMPLIFIED_POST_LAYOUTS],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_carouselitem_link_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_html",
            field=models.TextField(blank=True, verbose_name="Beitrag"),
        ),
        migrations.RunPython(
            seed_simplified_post_layouts_and_body_html,
            remove_simplified_post_layouts,
        ),
    ]
