# Generated by Django 5.2.16 on 2026-07-18 18:50

import apps.documents.models
import apps.documents.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Dokumentkategorie',
                'verbose_name_plural': 'Dokumentkategorien',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('visibility', models.CharField(choices=[('all_members', 'Alle Mitglieder'), ('selected_groups', 'Ausgewaehlte Gruppen'), ('selected_users', 'Ausgewaehlte Benutzer'), ('functionaries', 'Funktionstraeger'), ('highly_sensitive', 'Besonders sensibel')], default='all_members', max_length=30, verbose_name='Sichtbarkeit')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veroeffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veroeffentlicht am')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Gueltig bis')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am')),
                ('version_counter', models.PositiveIntegerField(default=0, verbose_name='Versionszaehler')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='visible_documents', to='auth.group', verbose_name='Erlaubte Gruppen')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='directly_visible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Erlaubte Benutzer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'ordering': ['title', 'pk'],
                'permissions': [('manage_publication_documents', 'Can manage publication documents'), ('manage_sensitive_documents', 'Can manage sensitive documents')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(verbose_name='Versionsnummer')),
                ('file', models.FileField(storage=apps.documents.storage.PrivateDocumentStorage(), upload_to=apps.documents.models.document_version_upload_to, verbose_name='Datei')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Originaldateiname')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-Type')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='Dateigroesse')),
                ('checksum', models.CharField(max_length=64, verbose_name='Pruefsumme')),
                ('change_note', models.CharField(blank=True, max_length=255, verbose_name='Aenderungsnotiz')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='Aktuelle Version'),
        ),
    ]
