from django.contrib.auth.models import Group, Permission
from django.core.management.base import BaseCommand, CommandError

ROLE_PERMISSION_MAP = {
    "member": [],
    "event_verantwortlich": [
        "events.view_event",
        "events.add_event",
        "events.change_event",
        "events.publish_event",
        "events.schedule_event",
        "events.cancel_event",
        "events.archive_event",
        "events.preview_event",
        "events.restore_event_revision",
        "events.view_eventrevision",
    ],
    "document_verantwortlich": [
        "documents.view_document",
        "documents.add_document",
        "documents.change_document",
        "documents.view_documentversion",
        "documents.manage_publication_documents",
    ],
    "web_aktuar": [
        "content.view_layoutpreset",
        "content.view_page",
        "content.add_page",
        "content.change_page",
        "content.view_pagesection",
        "content.add_pagesection",
        "content.change_pagesection",
        "content.publish_page",
        "content.preview_page",
        "content.restore_page_revision",
        "content.view_pagerevision",
        "content.view_post",
        "content.add_post",
        "content.change_post",
        "content.view_postblock",
        "content.add_postblock",
        "content.change_postblock",
        "content.publish_post",
        "content.preview_post",
        "content.pin_post_homepage",
        "content.restore_post_revision",
        "content.preview_unpublished_content",
        "content.view_postrevision",
        "content.view_carousel",
        "content.add_carousel",
        "content.change_carousel",
        "content.view_carouselitem",
        "content.add_carouselitem",
        "content.change_carouselitem",
        "content.preview_carousel",
        "content.restore_carousel_revision",
        "content.view_carouselrevision",
        "media_library.view_mediaasset",
        "media_library.add_mediaasset",
        "media_library.change_mediaasset",
        "media_library.publish_mediaasset",
        "events.view_event",
        "events.add_event",
        "events.change_event",
        "events.publish_event",
        "events.schedule_event",
        "events.cancel_event",
        "events.archive_event",
        "events.preview_event",
        "events.restore_event_revision",
        "events.view_eventrevision",
        "documents.view_document",
        "documents.add_document",
        "documents.change_document",
        "documents.view_documentversion",
        "documents.manage_publication_documents",
    ],
    "member_admin": [
        "accounts.add_accountinvitation",
        "accounts.view_accountinvitation",
        "members.view_memberprofile",
        "members.change_memberprofile",
        "members.manage_member_profiles",
        "members.view_sensitive_documents",
    ],
    "president": [
        "accounts.add_accountinvitation",
        "accounts.view_accountinvitation",
        "members.view_memberprofile",
        "members.change_memberprofile",
        "members.manage_member_profiles",
        "members.view_sensitive_documents",
        "audit.view_auditlogentry",
        "content.view_layoutpreset",
        "content.view_page",
        "content.add_page",
        "content.change_page",
        "content.view_pagesection",
        "content.add_pagesection",
        "content.change_pagesection",
        "content.publish_page",
        "content.preview_page",
        "content.restore_page_revision",
        "content.view_pagerevision",
        "content.view_post",
        "content.add_post",
        "content.change_post",
        "content.view_postblock",
        "content.add_postblock",
        "content.change_postblock",
        "content.publish_post",
        "content.preview_post",
        "content.pin_post_homepage",
        "content.restore_post_revision",
        "content.preview_unpublished_content",
        "content.view_postrevision",
        "content.view_carousel",
        "content.add_carousel",
        "content.change_carousel",
        "content.view_carouselitem",
        "content.add_carouselitem",
        "content.change_carouselitem",
        "content.preview_carousel",
        "content.restore_carousel_revision",
        "content.view_carouselrevision",
        "media_library.view_mediaasset",
        "media_library.add_mediaasset",
        "media_library.change_mediaasset",
        "media_library.publish_mediaasset",
        "events.view_event",
        "events.add_event",
        "events.change_event",
        "events.publish_event",
        "events.schedule_event",
        "events.cancel_event",
        "events.archive_event",
        "events.preview_event",
        "events.restore_event_revision",
        "events.view_eventrevision",
        "documents.view_document",
        "documents.add_document",
        "documents.change_document",
        "documents.view_documentversion",
        "documents.manage_publication_documents",
        "documents.manage_sensitive_documents",
    ],
    "system_admin": [
        "accounts.add_accountinvitation",
        "accounts.view_accountinvitation",
        "members.view_memberprofile",
        "members.change_memberprofile",
        "members.manage_member_profiles",
        "members.view_sensitive_documents",
        "audit.view_auditlogentry",
        "content.view_layoutpreset",
        "content.view_page",
        "content.add_page",
        "content.change_page",
        "content.view_pagesection",
        "content.add_pagesection",
        "content.change_pagesection",
        "content.publish_page",
        "content.preview_page",
        "content.restore_page_revision",
        "content.view_pagerevision",
        "content.view_post",
        "content.add_post",
        "content.change_post",
        "content.view_postblock",
        "content.add_postblock",
        "content.change_postblock",
        "content.publish_post",
        "content.preview_post",
        "content.pin_post_homepage",
        "content.restore_post_revision",
        "content.preview_unpublished_content",
        "content.view_postrevision",
        "content.view_carousel",
        "content.add_carousel",
        "content.change_carousel",
        "content.view_carouselitem",
        "content.add_carouselitem",
        "content.change_carouselitem",
        "content.preview_carousel",
        "content.restore_carousel_revision",
        "content.view_carouselrevision",
        "media_library.view_mediaasset",
        "media_library.add_mediaasset",
        "media_library.change_mediaasset",
        "media_library.publish_mediaasset",
        "media_library.manage_private_mediaasset",
        "events.view_event",
        "events.add_event",
        "events.change_event",
        "events.publish_event",
        "events.schedule_event",
        "events.cancel_event",
        "events.archive_event",
        "events.preview_event",
        "events.restore_event_revision",
        "events.view_eventrevision",
        "documents.view_document",
        "documents.add_document",
        "documents.change_document",
        "documents.view_documentversion",
        "documents.manage_publication_documents",
        "documents.manage_sensitive_documents",
    ],
}


class Command(BaseCommand):
    help = "Create and synchronize the default role groups for the members area."

    def handle(self, *args, **options):
        permission_index = {
            f"{permission.content_type.app_label}.{permission.codename}": permission
            for permission in Permission.objects.select_related("content_type")
        }

        for group_name, permission_labels in ROLE_PERMISSION_MAP.items():
            group, created = Group.objects.get_or_create(name=group_name)
            permissions = []
            missing = []

            for label in permission_labels:
                permission = permission_index.get(label)
                if permission is None:
                    missing.append(label)
                else:
                    permissions.append(permission)

            if missing:
                raise CommandError(
                    f"Missing permissions for group {group_name}: {', '.join(missing)}"
                )

            group.permissions.set(permissions)
            action = "Created" if created else "Updated"
            self.stdout.write(
                self.style.SUCCESS(
                    f"{action} group {group_name} with {len(permissions)} permissions."
                )
            )
