# Generated by Django 5.2.16 on 2026-07-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cms/media/', verbose_name='Datei')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt-Text')),
                ('is_decorative', models.BooleanField(default=False, verbose_name='Dekoratives Bild')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Bildlegende')),
                ('credit', models.CharField(blank=True, max_length=255, verbose_name='Urheber oder Quelle')),
                ('captured_on', models.DateField(blank=True, null=True, verbose_name='Aufnahmedatum')),
                ('visibility', models.CharField(choices=[('public', 'Oeffentlich'), ('members', 'Nur Mitglieder'), ('private', 'Privat')], default='public', max_length=20, verbose_name='Sichtbarkeit')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veroeffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, verbose_name='Dateigroesse')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='MIME-Type')),
                ('width', models.PositiveIntegerField(default=0, editable=False, verbose_name='Breite')),
                ('height', models.PositiveIntegerField(default=0, editable=False, verbose_name='Hoehe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'pk'],
                'permissions': [('publish_mediaasset', 'Can publish media assets'), ('manage_private_mediaasset', 'Can manage private media assets')],
            },
        ),
    ]
